import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SideList from "@/components/Sideber";
import HadisList from "./Hadis/HadisList/page";
import HadisSideBer from "@/components/HadisSideBer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className }>
        <div className="md:bg-white bg-gray-100">
        <Navbar/>
        <div className="flex md:flex-row flex-col-reverse">
        <SideList/>
        {children}
        </div>
        </div>
        </body>
    </html>
  );
}
